networks:
  app-network:
    driver: bridge

services:
  caddy:
    image: caddy:latest
    container_name: librebox_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    environment:
      - ACME_AGREE=true
    privileged: true
    networks:
      - app-network
    depends_on:
      - fastapi

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    env_file:
      - .gluetun.env
    privileged: true
    volumes:
      - ./gluetun:/gluetun
    ports:
      - "51413:51413"
    networks:
      - app-network
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: "service:gluetun"
    env_file:
      - .transmission.env
    privileged: true
    volumes:
      - downloads:/downloads
      - ./transmission-config:/config
    restart: unless-stopped
    depends_on:
      - gluetun

  migrate:
    image: amacneil/dbmate:latest
    command: ["up"]
    env_file:
      - .env
    volumes:
      - ./db/migrations:/db/migrations:ro
      - database:/database
    privileged: true

  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: librebox_fastapi
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - downloads:/app/downloads
      - database:/app/database
    depends_on:
      transmission:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    networks:
      - app-network
volumes:
  downloads:
  caddy-data:
  caddy-config:
  database:
