services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    env_file:
      - .gluetun.env
    volumes:
      - ./gluetun:/gluetun
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /Téléchargements:/downloads
      - ./transmission-config:/config
    restart: unless-stopped
    depends_on:
      - gluetun

  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: streamer_fastapi
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - /Téléchargements:/app/data
    depends_on:
      - transmission
