[project]
name = "bauxite"
version = "0.1.0"
description = "An open-source seedbox built with ease of use in mind."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.5",
    "aiosqlite>=0.22.1",
    "fastapi[standard]>=0.136.0",
    "pytest>=9.0.3",
    "transmission-rpc==8.0.0a4",
    "typer>=0.24.1",
]
